apiVersion: v1
kind: Pod
metadata:
  name: pod-1
  labels:
    app: myapp
    type: server
spec:
  containers:
  - name: nginx-container
    image: nginx
    ports: 
    - containerPort: 80
      protocal: TCP
  
  - name: http-container
    image: http
    ports:
    - containerPort: 8080
      protocal: TCP